/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChannelInfo = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Attachment = IDL.Vec(IDL.Nat8);
export const Post = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'attachments' : IDL.Vec(Attachment),
  'authorPrincipal' : IDL.Principal,
});
export const NewServerParams = IDL.Record({ 'name' : IDL.Text });
export const ServerInfo = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Text,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Opt(IDL.Text),
  'avatarAttachment' : IDL.Opt(Attachment),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'attachments' : IDL.Vec(Attachment),
  'authorPrincipal' : IDL.Principal,
});
export const ChannelView = IDL.Record({
  'id' : IDL.Text,
  'messages' : IDL.Vec(Message),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserSearchResult = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelInfo], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Vec(Attachment), IDL.Opt(IDL.Text)],
      [Post],
      [],
    ),
  'createServer' : IDL.Func([NewServerParams], [ServerInfo], []),
  'deleteChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteServer' : IDL.Func([IDL.Text], [], []),
  'editChannel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'editServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllChannels' : IDL.Func([IDL.Text], [IDL.Vec(ChannelInfo)], ['query']),
  'getAllServers' : IDL.Func([], [IDL.Vec(ServerInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(ChannelView)],
      ['query'],
    ),
  'getDirectMessages' : IDL.Func(
      [IDL.Principal, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getLatestPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getNewMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getOlderDirectMessages' : IDL.Func(
      [IDL.Principal, IDL.Int, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getOlderMessages' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getOlderPosts' : IDL.Func([IDL.Int, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getServer' : IDL.Func([IDL.Text], [IDL.Opt(ServerInfo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserSearchResult)], ['query']),
  'sendDirectMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Vec(Attachment), IDL.Opt(IDL.Text)],
      [Message],
      [],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Attachment), IDL.Opt(IDL.Text)],
      [Message],
      [],
    ),
  'uploadAttachment' : IDL.Func(
      [ExternalBlob, IDL.Text, IDL.Nat],
      [Attachment],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChannelInfo = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Attachment = IDL.Vec(IDL.Nat8);
  const Post = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'attachments' : IDL.Vec(Attachment),
    'authorPrincipal' : IDL.Principal,
  });
  const NewServerParams = IDL.Record({ 'name' : IDL.Text });
  const ServerInfo = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Text,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Opt(IDL.Text),
    'avatarAttachment' : IDL.Opt(Attachment),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'attachments' : IDL.Vec(Attachment),
    'authorPrincipal' : IDL.Principal,
  });
  const ChannelView = IDL.Record({
    'id' : IDL.Text,
    'messages' : IDL.Vec(Message),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserSearchResult = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelInfo], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Vec(Attachment), IDL.Opt(IDL.Text)],
        [Post],
        [],
      ),
    'createServer' : IDL.Func([NewServerParams], [ServerInfo], []),
    'deleteChannel' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteServer' : IDL.Func([IDL.Text], [], []),
    'editChannel' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'editServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllChannels' : IDL.Func([IDL.Text], [IDL.Vec(ChannelInfo)], ['query']),
    'getAllServers' : IDL.Func([], [IDL.Vec(ServerInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(ChannelView)],
        ['query'],
      ),
    'getDirectMessages' : IDL.Func(
        [IDL.Principal, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getLatestPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getNewMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOlderDirectMessages' : IDL.Func(
        [IDL.Principal, IDL.Int, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOlderMessages' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getOlderPosts' : IDL.Func([IDL.Int, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getServer' : IDL.Func([IDL.Text], [IDL.Opt(ServerInfo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserSearchResult)],
        ['query'],
      ),
    'sendDirectMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Vec(Attachment), IDL.Opt(IDL.Text)],
        [Message],
        [],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Attachment), IDL.Opt(IDL.Text)],
        [Message],
        [],
      ),
    'uploadAttachment' : IDL.Func(
        [ExternalBlob, IDL.Text, IDL.Nat],
        [Attachment],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };