/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Attachment = Uint8Array;
export interface ChannelInfo { 'id' : string, 'name' : string }
export interface ChannelView {
  'id' : string,
  'messages' : Array<Message>,
  'name' : string,
  'createdAt' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : string,
  'content' : string,
  'author' : string,
  'imageUrl' : [] | [string],
  'timestamp' : bigint,
  'attachments' : Array<Attachment>,
  'authorPrincipal' : Principal,
}
export interface NewServerParams { 'name' : string }
export interface Post {
  'id' : string,
  'content' : string,
  'author' : string,
  'imageUrl' : [] | [string],
  'timestamp' : bigint,
  'attachments' : Array<Attachment>,
  'authorPrincipal' : Principal,
}
export interface ServerInfo { 'id' : string, 'owner' : string, 'name' : string }
export interface UserProfile {
  'displayName' : string,
  'avatarUrl' : [] | [string],
  'avatarAttachment' : [] | [Attachment],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSearchResult {
  'principal' : Principal,
  'displayName' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChannel' : ActorMethod<[string, string], ChannelInfo>,
  'createPost' : ActorMethod<[string, Array<Attachment>, [] | [string]], Post>,
  'createServer' : ActorMethod<[NewServerParams], ServerInfo>,
  'deleteChannel' : ActorMethod<[string, string], undefined>,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteServer' : ActorMethod<[string], undefined>,
  'editChannel' : ActorMethod<[string, string, string], undefined>,
  'editServer' : ActorMethod<[string, string], undefined>,
  'getAllChannels' : ActorMethod<[string], Array<ChannelInfo>>,
  'getAllServers' : ActorMethod<[], Array<ServerInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[string, string], [] | [ChannelView]>,
  'getDirectMessages' : ActorMethod<[Principal, bigint], Array<Message>>,
  'getLatestPosts' : ActorMethod<[bigint], Array<Post>>,
  'getNewMessages' : ActorMethod<[string, string, bigint], Array<Message>>,
  'getOlderDirectMessages' : ActorMethod<
    [Principal, bigint, bigint],
    Array<Message>
  >,
  'getOlderMessages' : ActorMethod<
    [string, string, bigint, bigint],
    Array<Message>
  >,
  'getOlderPosts' : ActorMethod<[bigint, bigint], Array<Post>>,
  'getServer' : ActorMethod<[string], [] | [ServerInfo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserSearchResult>>,
  'sendDirectMessage' : ActorMethod<
    [Principal, string, Array<Attachment>, [] | [string]],
    Message
  >,
  'sendMessage' : ActorMethod<
    [string, string, string, Array<Attachment>, [] | [string]],
    Message
  >,
  'uploadAttachment' : ActorMethod<[ExternalBlob, string, bigint], Attachment>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];