/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProfileVisibilityStatus {
    bio: FieldVisibility;
    displayName: FieldVisibility;
    joinDate: FieldVisibility;
    links: Array<FieldVisibility>;
    pronouns: FieldVisibility;
    avatar: FieldVisibility;
}
export interface ServerBranding {
    topic: string;
    icon?: string;
    banner?: string;
    description: string;
    bannerAttachment?: Attachment;
    iconAttachment?: Attachment;
}
export interface ChannelInfo {
    id: string;
    name: string;
}
export interface ServerInfoExtended {
    id: string;
    owner: string;
    ownerPrincipal: Principal;
    name: string;
    memberCount: bigint;
    inviteCode: string;
    branding: ServerBranding;
}
export interface ServerInfo {
    id: string;
    owner: string;
    ownerPrincipal: Principal;
    name: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface UserSearchResult {
    principal: Principal;
    displayName: string;
    isAdmin: boolean;
}
export interface ExtendedUserProfile {
    bio: string;
    displayName: string;
    joinDate: bigint;
    displayNameVisibility: FieldVisibility;
    bioVisibility: FieldVisibility;
    linksVisibilities: Array<FieldVisibility>;
    links: Array<string>;
    pronouns?: string;
    avatarUrl?: string;
    avatarVisibility: FieldVisibility;
    avatarAttachment?: Attachment;
    joinDateVisibility: FieldVisibility;
    pronounsVisibility: FieldVisibility;
}
export interface PublicUserProfile {
    bio: string;
    displayName: string;
    joinDate: bigint;
    links: Array<string>;
    pronouns?: string;
    avatarUrl?: string;
}
export interface NewServerParams {
    name: string;
}
export type Attachment = Uint8Array;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FieldVisibility {
    privateVisibility = "privateVisibility",
    publicVisibility = "publicVisibility"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createChannel(serverId: string, name: string): Promise<ChannelInfo>;
    createServer(params: NewServerParams): Promise<ServerInfo>;
    deleteServer(serverId: string, confirmationName: string): Promise<void>;
    editServer(serverId: string, newName: string): Promise<void>;
    getAllServers(): Promise<Array<ServerInfo>>;
    getCallerUserProfile(): Promise<ExtendedUserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProfileVisibility(user: Principal): Promise<ProfileVisibilityStatus | null>;
    getServer(serverId: string): Promise<ServerInfo | null>;
    getServerExtended(serverId: string): Promise<ServerInfoExtended | null>;
    getServerInviteCode(serverId: string): Promise<string | null>;
    getUserProfile(user: Principal): Promise<PublicUserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: ExtendedUserProfile): Promise<void>;
    searchUsers(searchTerm: string): Promise<Array<UserSearchResult>>;
    updateProfileFieldVisibility(field: string, value: bigint | null, visibility: FieldVisibility): Promise<void>;
}
import type { Attachment as _Attachment, ExtendedUserProfile as _ExtendedUserProfile, FieldVisibility as _FieldVisibility, ProfileVisibilityStatus as _ProfileVisibilityStatus, PublicUserProfile as _PublicUserProfile, ServerBranding as _ServerBranding, ServerInfo as _ServerInfo, ServerInfoExtended as _ServerInfoExtended, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createChannel(arg0: string, arg1: string): Promise<ChannelInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.createChannel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createChannel(arg0, arg1);
            return result;
        }
    }
    async createServer(arg0: NewServerParams): Promise<ServerInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.createServer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServer(arg0);
            return result;
        }
    }
    async deleteServer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteServer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteServer(arg0, arg1);
            return result;
        }
    }
    async editServer(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editServer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editServer(arg0, arg1);
            return result;
        }
    }
    async getAllServers(): Promise<Array<ServerInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServers();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<ExtendedUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfileVisibility(arg0: Principal): Promise<ProfileVisibilityStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileVisibility(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileVisibility(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServer(arg0: string): Promise<ServerInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServer(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServer(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServerExtended(arg0: string): Promise<ServerInfoExtended | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerExtended(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerExtended(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServerInviteCode(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServerInviteCode(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServerInviteCode(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<PublicUserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: ExtendedUserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_ExtendedUserProfile_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_ExtendedUserProfile_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchUsers(arg0: string): Promise<Array<UserSearchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsers(arg0);
            return result;
        }
    }
    async updateProfileFieldVisibility(arg0: string, arg1: bigint | null, arg2: FieldVisibility): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileFieldVisibility(arg0, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), to_candid_FieldVisibility_n34(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileFieldVisibility(arg0, to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), to_candid_FieldVisibility_n34(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_ExtendedUserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtendedUserProfile): ExtendedUserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_FieldVisibility_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldVisibility): FieldVisibility {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileVisibilityStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileVisibilityStatus): ProfileVisibilityStatus {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PublicUserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PublicUserProfile): PublicUserProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ServerBranding_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServerBranding): ServerBranding {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_ServerInfoExtended_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServerInfoExtended): ServerInfoExtended {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExtendedUserProfile]): ExtendedUserProfile | null {
    return value.length === 0 ? null : from_candid_ExtendedUserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Attachment]): Attachment | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfileVisibilityStatus]): ProfileVisibilityStatus | null {
    return value.length === 0 ? null : from_candid_ProfileVisibilityStatus_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServerInfo]): ServerInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServerInfoExtended]): ServerInfoExtended | null {
    return value.length === 0 ? null : from_candid_ServerInfoExtended_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PublicUserProfile]): PublicUserProfile | null {
    return value.length === 0 ? null : from_candid_PublicUserProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    joinDate: bigint;
    displayNameVisibility: _FieldVisibility;
    bioVisibility: _FieldVisibility;
    linksVisibilities: Array<_FieldVisibility>;
    links: Array<string>;
    pronouns: [] | [string];
    avatarUrl: [] | [string];
    avatarVisibility: _FieldVisibility;
    avatarAttachment: [] | [_Attachment];
    joinDateVisibility: _FieldVisibility;
    pronounsVisibility: _FieldVisibility;
}): {
    bio: string;
    displayName: string;
    joinDate: bigint;
    displayNameVisibility: FieldVisibility;
    bioVisibility: FieldVisibility;
    linksVisibilities: Array<FieldVisibility>;
    links: Array<string>;
    pronouns?: string;
    avatarUrl?: string;
    avatarVisibility: FieldVisibility;
    avatarAttachment?: Attachment;
    joinDateVisibility: FieldVisibility;
    pronounsVisibility: FieldVisibility;
} {
    return {
        bio: value.bio,
        displayName: value.displayName,
        joinDate: value.joinDate,
        displayNameVisibility: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.displayNameVisibility),
        bioVisibility: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.bioVisibility),
        linksVisibilities: from_candid_vec_n15(_uploadFile, _downloadFile, value.linksVisibilities),
        links: value.links,
        pronouns: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pronouns)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.avatarUrl)),
        avatarVisibility: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.avatarVisibility),
        avatarAttachment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.avatarAttachment)),
        joinDateVisibility: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.joinDateVisibility),
        pronounsVisibility: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.pronounsVisibility)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: _FieldVisibility;
    displayName: _FieldVisibility;
    joinDate: _FieldVisibility;
    links: Array<_FieldVisibility>;
    pronouns: _FieldVisibility;
    avatar: _FieldVisibility;
}): {
    bio: FieldVisibility;
    displayName: FieldVisibility;
    joinDate: FieldVisibility;
    links: Array<FieldVisibility>;
    pronouns: FieldVisibility;
    avatar: FieldVisibility;
} {
    return {
        bio: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.bio),
        displayName: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.displayName),
        joinDate: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.joinDate),
        links: from_candid_vec_n15(_uploadFile, _downloadFile, value.links),
        pronouns: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.pronouns),
        avatar: from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, value.avatar)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: string;
    ownerPrincipal: Principal;
    name: string;
    memberCount: bigint;
    inviteCode: string;
    branding: _ServerBranding;
}): {
    id: string;
    owner: string;
    ownerPrincipal: Principal;
    name: string;
    memberCount: bigint;
    inviteCode: string;
    branding: ServerBranding;
} {
    return {
        id: value.id,
        owner: value.owner,
        ownerPrincipal: value.ownerPrincipal,
        name: value.name,
        memberCount: value.memberCount,
        inviteCode: value.inviteCode,
        branding: from_candid_ServerBranding_n27(_uploadFile, _downloadFile, value.branding)
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    topic: string;
    icon: [] | [string];
    banner: [] | [string];
    description: string;
    bannerAttachment: [] | [_Attachment];
    iconAttachment: [] | [_Attachment];
}): {
    topic: string;
    icon?: string;
    banner?: string;
    description: string;
    bannerAttachment?: Attachment;
    iconAttachment?: Attachment;
} {
    return {
        topic: value.topic,
        icon: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.icon)),
        banner: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.banner)),
        description: value.description,
        bannerAttachment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.bannerAttachment)),
        iconAttachment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.iconAttachment))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    joinDate: bigint;
    links: Array<string>;
    pronouns: [] | [string];
    avatarUrl: [] | [string];
}): {
    bio: string;
    displayName: string;
    joinDate: bigint;
    links: Array<string>;
    pronouns?: string;
    avatarUrl?: string;
} {
    return {
        bio: value.bio,
        displayName: value.displayName,
        joinDate: value.joinDate,
        links: value.links,
        pronouns: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.pronouns)),
        avatarUrl: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.avatarUrl))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    privateVisibility: null;
} | {
    publicVisibility: null;
}): FieldVisibility {
    return "privateVisibility" in value ? FieldVisibility.privateVisibility : "publicVisibility" in value ? FieldVisibility.publicVisibility : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FieldVisibility>): Array<FieldVisibility> {
    return value.map((x)=>from_candid_FieldVisibility_n13(_uploadFile, _downloadFile, x));
}
function to_candid_ExtendedUserProfile_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExtendedUserProfile): _ExtendedUserProfile {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_FieldVisibility_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldVisibility): _FieldVisibility {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    joinDate: bigint;
    displayNameVisibility: FieldVisibility;
    bioVisibility: FieldVisibility;
    linksVisibilities: Array<FieldVisibility>;
    links: Array<string>;
    pronouns?: string;
    avatarUrl?: string;
    avatarVisibility: FieldVisibility;
    avatarAttachment?: Attachment;
    joinDateVisibility: FieldVisibility;
    pronounsVisibility: FieldVisibility;
}): {
    bio: string;
    displayName: string;
    joinDate: bigint;
    displayNameVisibility: _FieldVisibility;
    bioVisibility: _FieldVisibility;
    linksVisibilities: Array<_FieldVisibility>;
    links: Array<string>;
    pronouns: [] | [string];
    avatarUrl: [] | [string];
    avatarVisibility: _FieldVisibility;
    avatarAttachment: [] | [_Attachment];
    joinDateVisibility: _FieldVisibility;
    pronounsVisibility: _FieldVisibility;
} {
    return {
        bio: value.bio,
        displayName: value.displayName,
        joinDate: value.joinDate,
        displayNameVisibility: to_candid_FieldVisibility_n34(_uploadFile, _downloadFile, value.displayNameVisibility),
        bioVisibility: to_candid_FieldVisibility_n34(_uploadFile, _downloadFile, value.bioVisibility),
        linksVisibilities: to_candid_vec_n36(_uploadFile, _downloadFile, value.linksVisibilities),
        links: value.links,
        pronouns: value.pronouns ? candid_some(value.pronouns) : candid_none(),
        avatarUrl: value.avatarUrl ? candid_some(value.avatarUrl) : candid_none(),
        avatarVisibility: to_candid_FieldVisibility_n34(_uploadFile, _downloadFile, value.avatarVisibility),
        avatarAttachment: value.avatarAttachment ? candid_some(value.avatarAttachment) : candid_none(),
        joinDateVisibility: to_candid_FieldVisibility_n34(_uploadFile, _downloadFile, value.joinDateVisibility),
        pronounsVisibility: to_candid_FieldVisibility_n34(_uploadFile, _downloadFile, value.pronounsVisibility)
    };
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldVisibility): {
    privateVisibility: null;
} | {
    publicVisibility: null;
} {
    return value == FieldVisibility.privateVisibility ? {
        privateVisibility: null
    } : value == FieldVisibility.publicVisibility ? {
        publicVisibility: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FieldVisibility>): Array<_FieldVisibility> {
    return value.map((x)=>to_candid_FieldVisibility_n34(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
