/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Attachment = Uint8Array;
export interface ChannelInfo { 'id' : string, 'name' : string }
export interface ExtendedUserProfile {
  'bio' : string,
  'displayName' : string,
  'joinDate' : bigint,
  'displayNameVisibility' : FieldVisibility,
  'bioVisibility' : FieldVisibility,
  'linksVisibilities' : Array<FieldVisibility>,
  'links' : Array<string>,
  'pronouns' : [] | [string],
  'avatarUrl' : [] | [string],
  'avatarVisibility' : FieldVisibility,
  'avatarAttachment' : [] | [Attachment],
  'joinDateVisibility' : FieldVisibility,
  'pronounsVisibility' : FieldVisibility,
}
export type FieldVisibility = { 'privateVisibility' : null } |
  { 'publicVisibility' : null };
export interface NewServerParams { 'name' : string }
export interface ProfileVisibilityStatus {
  'bio' : FieldVisibility,
  'displayName' : FieldVisibility,
  'joinDate' : FieldVisibility,
  'links' : Array<FieldVisibility>,
  'pronouns' : FieldVisibility,
  'avatar' : FieldVisibility,
}
export interface PublicUserProfile {
  'bio' : string,
  'displayName' : string,
  'joinDate' : bigint,
  'links' : Array<string>,
  'pronouns' : [] | [string],
  'avatarUrl' : [] | [string],
}
export interface ServerBranding {
  'topic' : string,
  'icon' : [] | [string],
  'banner' : [] | [string],
  'description' : string,
  'bannerAttachment' : [] | [Attachment],
  'iconAttachment' : [] | [Attachment],
}
export interface ServerInfo {
  'id' : string,
  'owner' : string,
  'ownerPrincipal' : Principal,
  'name' : string,
}
export interface ServerInfoExtended {
  'id' : string,
  'owner' : string,
  'ownerPrincipal' : Principal,
  'name' : string,
  'memberCount' : bigint,
  'inviteCode' : string,
  'branding' : ServerBranding,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserSearchResult {
  'principal' : Principal,
  'displayName' : string,
  'isAdmin' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChannel' : ActorMethod<[string, string], ChannelInfo>,
  'createServer' : ActorMethod<[NewServerParams], ServerInfo>,
  'deleteServer' : ActorMethod<[string, string], undefined>,
  'editServer' : ActorMethod<[string, string], undefined>,
  'getAllServers' : ActorMethod<[], Array<ServerInfo>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [ExtendedUserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfileVisibility' : ActorMethod<
    [Principal],
    [] | [ProfileVisibilityStatus]
  >,
  'getServer' : ActorMethod<[string], [] | [ServerInfo]>,
  'getServerExtended' : ActorMethod<[string], [] | [ServerInfoExtended]>,
  'getServerInviteCode' : ActorMethod<[string], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [PublicUserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[ExtendedUserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<UserSearchResult>>,
  'updateProfileFieldVisibility' : ActorMethod<
    [string, [] | [bigint], FieldVisibility],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];