/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChannelInfo = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const NewServerParams = IDL.Record({ 'name' : IDL.Text });
export const ServerInfo = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
});
export const FieldVisibility = IDL.Variant({
  'privateVisibility' : IDL.Null,
  'publicVisibility' : IDL.Null,
});
export const Attachment = IDL.Vec(IDL.Nat8);
export const ExtendedUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'joinDate' : IDL.Int,
  'displayNameVisibility' : FieldVisibility,
  'bioVisibility' : FieldVisibility,
  'linksVisibilities' : IDL.Vec(FieldVisibility),
  'links' : IDL.Vec(IDL.Text),
  'pronouns' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
  'avatarVisibility' : FieldVisibility,
  'avatarAttachment' : IDL.Opt(Attachment),
  'joinDateVisibility' : FieldVisibility,
  'pronounsVisibility' : FieldVisibility,
});
export const ProfileVisibilityStatus = IDL.Record({
  'bio' : FieldVisibility,
  'displayName' : FieldVisibility,
  'joinDate' : FieldVisibility,
  'links' : IDL.Vec(FieldVisibility),
  'pronouns' : FieldVisibility,
  'avatar' : FieldVisibility,
});
export const ServerBranding = IDL.Record({
  'topic' : IDL.Text,
  'icon' : IDL.Opt(IDL.Text),
  'banner' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'bannerAttachment' : IDL.Opt(Attachment),
  'iconAttachment' : IDL.Opt(Attachment),
});
export const ServerInfoExtended = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Text,
  'ownerPrincipal' : IDL.Principal,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'inviteCode' : IDL.Text,
  'branding' : ServerBranding,
});
export const PublicUserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'joinDate' : IDL.Int,
  'links' : IDL.Vec(IDL.Text),
  'pronouns' : IDL.Opt(IDL.Text),
  'avatarUrl' : IDL.Opt(IDL.Text),
});
export const UserSearchResult = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'isAdmin' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelInfo], []),
  'createServer' : IDL.Func([NewServerParams], [ServerInfo], []),
  'deleteServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'editServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllServers' : IDL.Func([], [IDL.Vec(ServerInfo)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(ExtendedUserProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfileVisibility' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProfileVisibilityStatus)],
      ['query'],
    ),
  'getServer' : IDL.Func([IDL.Text], [IDL.Opt(ServerInfo)], ['query']),
  'getServerExtended' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ServerInfoExtended)],
      ['query'],
    ),
  'getServerInviteCode' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([ExtendedUserProfile], [], []),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserSearchResult)], ['query']),
  'updateProfileFieldVisibility' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), FieldVisibility],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChannelInfo = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const NewServerParams = IDL.Record({ 'name' : IDL.Text });
  const ServerInfo = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
  });
  const FieldVisibility = IDL.Variant({
    'privateVisibility' : IDL.Null,
    'publicVisibility' : IDL.Null,
  });
  const Attachment = IDL.Vec(IDL.Nat8);
  const ExtendedUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'joinDate' : IDL.Int,
    'displayNameVisibility' : FieldVisibility,
    'bioVisibility' : FieldVisibility,
    'linksVisibilities' : IDL.Vec(FieldVisibility),
    'links' : IDL.Vec(IDL.Text),
    'pronouns' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
    'avatarVisibility' : FieldVisibility,
    'avatarAttachment' : IDL.Opt(Attachment),
    'joinDateVisibility' : FieldVisibility,
    'pronounsVisibility' : FieldVisibility,
  });
  const ProfileVisibilityStatus = IDL.Record({
    'bio' : FieldVisibility,
    'displayName' : FieldVisibility,
    'joinDate' : FieldVisibility,
    'links' : IDL.Vec(FieldVisibility),
    'pronouns' : FieldVisibility,
    'avatar' : FieldVisibility,
  });
  const ServerBranding = IDL.Record({
    'topic' : IDL.Text,
    'icon' : IDL.Opt(IDL.Text),
    'banner' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'bannerAttachment' : IDL.Opt(Attachment),
    'iconAttachment' : IDL.Opt(Attachment),
  });
  const ServerInfoExtended = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Text,
    'ownerPrincipal' : IDL.Principal,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'inviteCode' : IDL.Text,
    'branding' : ServerBranding,
  });
  const PublicUserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'joinDate' : IDL.Int,
    'links' : IDL.Vec(IDL.Text),
    'pronouns' : IDL.Opt(IDL.Text),
    'avatarUrl' : IDL.Opt(IDL.Text),
  });
  const UserSearchResult = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'isAdmin' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChannel' : IDL.Func([IDL.Text, IDL.Text], [ChannelInfo], []),
    'createServer' : IDL.Func([NewServerParams], [ServerInfo], []),
    'deleteServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'editServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllServers' : IDL.Func([], [IDL.Vec(ServerInfo)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(ExtendedUserProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfileVisibility' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProfileVisibilityStatus)],
        ['query'],
      ),
    'getServer' : IDL.Func([IDL.Text], [IDL.Opt(ServerInfo)], ['query']),
    'getServerExtended' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ServerInfoExtended)],
        ['query'],
      ),
    'getServerInviteCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([ExtendedUserProfile], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserSearchResult)],
        ['query'],
      ),
    'updateProfileFieldVisibility' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), FieldVisibility],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };